name: Quality

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:

jobs:
  Quality:
    uses: gesslar/Maint/.github/workflows/QualityTheme.yaml@main
    secrets: inherit
    with:
      theme_files: "src/*.sassy.yaml"
      strict: "no"
